version: '3.8'
services:
  backend:
    build: ./backend
    image: backend-app:1.0.1
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - mynet


  frontend:
    build: ./frontend
    image: frontend-app:1.0.0
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynet


  mongo:
    image: mongo:latest 
    container_name: mongo
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo-data:/data/db
    networks:
      - mynet


volumes:
  mongo-data:

networks:
  mynet:
    driver: bridge